week_five/faux-twitter/config/routes.rb
FauxTwitter::Application.routes.draw do
  
  get "main/index"
  
  get "main/find_me_info"

  get "user_preference/show"

  get "user_preference/new"

  get "user_preference/add"

  get "user_preference/edit"

  get "user_preference/destroy"
  
  get "signup/new"
  
  post "signup/create"

  
  
  match 'home' => "main#index"
  match 'signup' => "signup#new"
  
  match 'session/destroy' => "session#destroy"
  match 'status/new' => "status#new"

  resources :user
  resources :status 
  resources :session
  #resources :signup

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

    root :to => "main#index"
end

week_five/faux-twitter/app/models/user.rb
class User < ActiveRecord::Base
    #User(id: integer, username: string, password: string, email: string, created_at: datetime, updated_at: datetime)
    puts "USER BEING CREATED"
    validates :username, :presence => true
    validates :username, :uniqueness => true
    validates :email, 
        :length => {:minimum => 3, :maximum => 254},
        :uniqueness => true,
        :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
        
    has_many  :user_statuses
end

week_five/faux-twitter/app/models/user_additional_profiles.rb
class UserAdditionalProfiles < ActiveRecord::Base
end

week_five/faux-twitter/app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
end

week_five/faux-twitter/app/models/user_status.rb
class UserStatus < ActiveRecord::Base
    #UserStatus(id: integer, user_id: integer, status_update: text, pub_date: datetime, created_at: datetime, updated_at: datetime)
    
    belongs_to :user
    validates :status_update, :presence => true, :uniqueness => true
end

week_five/faux-twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery

    before_filter   :check_title


    protected

    # If no one remembered the page title, no worries
    def check_title
        @page_title = "FauxTwitter"
    end



end

week_five/faux-twitter/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

week_five/faux-twitter/app/controllers/main_controller.rb
class MainController < ApplicationController
  #layout 'cool'
  
  def index
    # Welcome Screen
    # Get People In, Have them view some recent tweets or
    # sign up to write some of their own
    
    # If notices, let the user know
    # flash[:notice]
  end
  
  def find_me_info
      # add information into the page dynamically at run time
      # the_info goes into the partial
      the_info = params[:what_info] if params[:what_info].is_a? String
      
      @status = UserStatus.find(the_info)
      #render :text => "Last Tweet : #{@status.status_update}"
      
      # the partial is rendered out using the local variable from the parameters params[:what_info]
      #render :text => @status.status_update
      render :partial => '/partials/add_content_now', :locals =>{:my_info => @status}
      
  end

end

week_five/faux-twitter/app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
        #User(id: integer, username: string, password: string, email: string, created_at: datetime, updated_at: datetime)
        # attempt to log a user in
        @user = User.new
    end

    def create
        # after a user has been checked out, send them here to initiate their session

        # Check to see if the user exists in the database?
        # Do they? If not, send them to our Sign up Page

        #Parameters: {"utf8"=>"✓", "authenticity_token"=>"f25nQNcu2rDOzfzaa20si99EF+z29cMivczsr1p0fos=", 
        #"user"=>{"username"=>"matt", "password"=>"[FILTERED]"}, "commit"=>"Log In"}

        if params[:commit] == "Log In"
            @current = User.find_by_username_and_password(params[:user][:username],params[:user][:password])
            if @current.is_a? User
                # Start Saving Session Info for the User
                puts params[:user].inspect
                session[:user] = {}
                session[:user]["username"] = @current["username"] if !@current["username"].nil?
                session[:user]["is_active"] = true
                session[:user]["email"] = @current["email"]
                session[:user]["id"] = @current[:id]
                flash[:notice] = "logged in sucessfully"
                redirect_to user_path(@current[:id])
            else
               flash[:error] = "Your Username and/or Password is incorrect"
               render :action => "new" 
            end
        else
            flash[:error] = "You need to login with our forms, don't try and hack the system"
            redirect_to signup_path 
        end
    end

    def destroy
        # want to log a user back out again
        # send them here to kill their session
        if session[:user]
           session[:user] = nil
           flash[:notice] = "You have been logged out."
           redirect_to home_path 
        end
    end

end

week_five/faux-twitter/app/controllers/signup_controller.rb
class SignupController < ApplicationController
    
    def new
        # get
        # User.new
        #User(id: integer, username: string, password: string, email: string, created_at: datetime, updated_at: datetime)
        @user = User.new
    end

    def create
        #Parameters: {"utf8"=>"✓", "authenticity_token"=>"f25nQNcu2rDOzfzaa20si99EF+z29cMivczsr1p0fos=", 
        #"user"=>{"username"=>"scotthaines", 
        #"password"=>"[FILTERED]", 
        # "email"=>"scott@convorelay.com"}, "commit"=>"Sign Up"}
        if params[:commit] == "Sign Up"
            # We know the user actually pressed a button to get here
            @user = User.new(params[:user])
            #if @user.save && !@user.new_record?
            if @user.save
                flash[:notice] = "Horray. You have completed your Signup. We were able to Save your Account."
                redirect_to home_path
            else
                if @user.errors
                    render :action => :new
                end 
                
            end
        end
    end
end

week_five/faux-twitter/app/controllers/status_controller.rb
class StatusController < ApplicationController
    
    def new
        #only if you are loggedin
        unless session[:user]
           redirect_to home_path 
        end
        @status = UserStatus.new
    end

    def create
        #render :inline => "Good Job, Twitting away"
        @user = User.find(session[:user]["id"])
        if @user.is_a? User
            if @user.user_statuses << UserStatus.create(:status_update => params["user_status"]["status_update"]) 
                flash[:notice] = "Tweet was saved"
                redirect_to user_path(@user.id)
            else
               flash[:error] = "Tweet wasn't saved."
               redirect_to :action => :new 
            end
        else
            flash[:error] = "Some issue here..."
           redirect_to :action => :new 
        end
    end

    def show
    end

    def edit
    end

    def destroy
    end

end

week_five/faux-twitter/app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
        #/user
        # list all users
        @users = User.find(:all,:conditions=>{},:limit => 10)
    end

    def show
        #/user/1
        # check you session, is this you?
        if session[:user]
            #render :inline => "This user is in session #{session[:user]["username"]}"
        end
    end

    def edit
        #/user/1/edit
    end

    def destroy
        #/user/1/destroy
    end

end

week_five/faux-twitter/app/controllers/user_preference_controller.rb
class UserPreferenceController < ApplicationController
  def show
  end

  def new
  end

  def add
  end

  def edit
  end

  def destroy
  end

end

week_five/faux-twitter/app/helpers/application_helper.rb
module ApplicationHelper
    
    def check_for_user_or_admin
        if session[:user]
           
        end
    end
    
end

week_five/faux-twitter/app/helpers/dashboard_helper.rb
module DashboardHelper
end

week_five/faux-twitter/app/helpers/main_helper.rb
module MainHelper
end

week_five/faux-twitter/app/helpers/session_helper.rb
module SessionHelper
end

week_five/faux-twitter/app/helpers/signup_helper.rb
module SignupHelper
end

week_five/faux-twitter/app/helpers/status_helper.rb
module StatusHelper
end

week_five/faux-twitter/app/helpers/user_helper.rb
module UserHelper
end

week_five/faux-twitter/app/helpers/user_preference_helper.rb
module UserPreferenceHelper
end

week_five/faux-twitter/app/views/main/index.html.erb
<% if flash[:notice] %>
	<div id="notices">
		<p><%= flash[:notice]%></p>
	</div>
<% end %>
<div id="content">
	<%= render 'partials/user_status', :locals => {:userid => 'all'}%>
	<div id="dynamic_information_div"></div>
	<a href="" id="event_button" >EVENT BUTTON</a>
	
</div>

week_five/faux-twitter/app/views/partials/_add_content_now.html.erb
<%
#my_info = @status from main_controller
@user = my_info.user
%>
<div id="add_content_now">
	
	<p>Welcome to our website,.... <%= @user.username %></p>
	<p><%= my_info.status_update %></p>
</div>

week_five/faux-twitter/app/views/partials/_main_header.html.erb
<div id="header">
	<h3>TwitSpace</h3>
	<div id="navigation">
		<ul>
			<li><%= link_to "Home", home_path %></li>
			<% if !session[:user] %>
				<li><%= link_to "Login", new_session_path%></li>
				<li><%= link_to "Sign Up", signup_path %></li>
			<% end %>
			<% if session[:user]%>
				<li><%= link_to "Profile", user_path(session[:user]["id"])%></li>
				<li><%= link_to "Twit", status_new_path %></li>
				<li><%= link_to "Logout", session_destroy_path %></li>
			<% end %>
		</ul>
	</div>
</div>

week_five/faux-twitter/app/views/partials/_user_status.html.erb
<%
  #userid
  # Get user with id of 4, find all statuses
	# unless userid == "all"
	#if userid != "all"
	#	@u = User.find(userid.to_i)
	#	@type = "single"
	#elsif userid.is_a? String
	#	@s = UserStatus.where(:user_id != 0)
	#	@type = "all"
	#end
%>
<% if @u.is_a? User %>
	<% @u.user_statuses.each do |status| %>
		<div class="status_update">
			<div class="user_status">
				<%= status.status_update %> 
			</div>
			<div class="user_status_time">	
				By <%= link_to @u.username ,user_path(@u.id),:class => 'user_highlight'%> <%= status.created_at.strftime("%b %d %Y %I:%M:%S")%></div>
			</div>
	<% end %>
<% elsif @type == "all"%>
	<% @s.each do |status| %>
		<div class="status_update">
			<div class="user_status">
				<%= status.status_update %> 
			</div>
			<div class="user_status_time">	
				By <%= link_to "#{status.user.username}" ,user_path(status.user.id),:class => 'user_highlight'%> <%= status.created_at.strftime("%b %d %Y %I:%M:%S")%></div>
			</div>
	<% end %>
<% else %>
	<p>No Tweets.</p>
<% end %>

week_five/faux-twitter/app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

week_five/faux-twitter/app/views/session/new.html.erb
<div class="main_form_wrapper">
	<% if flash[:errors]%>
	<div id="errors">
		<span class="error_span"><span class="spec_error"><%= flash[:errors]%></span></span>
	</div>
	<% end %>
	<%= form_for @user, :url => { :controller => 'session', :action => "create" }, :html => {:class => "user_forms"} do |f| %>
	<div class="block mtt mbt">
		<%= label_tag(:username, "Your Username",:class=>"mlt top_label") %>
		<%= f.text_field :username, :class => 'mlt mrt sinput'%>
	</div>
	<div class="block mtt mbt">
		<%= label_tag(:username, "Your Password",:class=>"mlt top_label") %>
		<%= f.password_field :password, :class => 'mlt mrt sinput'%>
	</div>
	<%= f.submit "Log In", :class => "glb_action_button mlt"%>
	<% end %>
</div>

week_five/faux-twitter/app/views/signup/create.html.erb
<h1>Signup#create</h1>
<p>Find me in app/views/signup/create.html.erb</p>

week_five/faux-twitter/app/views/signup/new.html.erb
<div class="main_form_wrapper">
	<% if @user.errors.count >= 1%>
	<div id="errors">
		<% @user.errors.each do |error,message|%>
			<span class="error_span"><span class="spec_error"><%= error %></span> <%= message %></span>
		<% end %>
	</div>
	<% end %>
	<%= form_for @user, :url => { :controller => 'signup', :action => "create" }, :html => {:class => "user_forms"} do |f| %>
	<div class="block mtt mbt">
		<%= label_tag(:username, "Select a Username",:class=>"mlt top_label") %>
		<%= f.text_field :username, :class => 'mlt mrt sinput'%>
	</div>
	<div class="block mtt mbt">
		<%= label_tag(:username, "Think up a Smart Password",:class=>"mlt top_label") %>
		<%= f.password_field :password, :class => 'mlt mrt sinput'%>
	</div>
	<div class="block mtt mbt">
		<%= label_tag(:username, "Let us know your real email.",:class=>"mlt top_label") %>
		<%= f.text_field :email, :class => 'mlt mrt sinput'%>
	</div>
	<%= f.submit "Sign Up", :class => "glb_action_button mlt"%>
	<% end %>
</div>

week_five/faux-twitter/app/views/status/destroy.html.erb
<h1>Status#destroy</h1>
<p>Find me in app/views/status/destroy.html.erb</p>

week_five/faux-twitter/app/views/status/edit.html.erb
<h1>Status#edit</h1>
<p>Find me in app/views/status/edit.html.erb</p>

week_five/faux-twitter/app/views/status/new.html.erb
<%
# new status for the user
#UserStatus(id: integer, user_id: integer, status_update: text, pub_date: datetime, created_at: datetime, updated_at: datetime)
%>
<% if flash[:error] %>
	<div id="errors">
		<span class="error_span"><span class="spec_error"><%= flash[:error]%></span></span>
	</div>
<% end %>
<%= form_for @status, :url => {:controller => :status, :action => :create}, :html => {:class => "user_forms"} do |f| %>
<div class="block mtt mbt">
	<%= label_tag(:status_update, "Status",:class=>"mlt top_label") %>
	<%= f.text_area :status_update, :class => 'mlt mrt sinput', :size=>"60x10"%>
</div>
<%= f.submit "Tweet", :class => "glb_action_button mlt"%>
<% end %>

week_five/faux-twitter/app/views/status/show.html.erb
<h1>Status#show</h1>
<p>Find me in app/views/status/show.html.erb</p>